apiVersion: v1
kind: Service
metadata:
  name: api-livros-service
  namespace: default
  labels:
    app: api-livros
    service: api-livros
spec:
  type: ClusterIP  # Tipo ClusterIP para exposição interna
  selector:
    app: api-livros  # Deve corresponder ao label do deployment
  ports:
  - port: 8000       # Porta do service
    targetPort: 8000 # Porta do container
    protocol: TCP
    name: http
  sessionAffinity: None